version: '3.9'
services:
    web:
        container_name: cdebrowser
        image: cdebrowser
        build: .
        ports:
            - 8080:80
        restart: always
       
        environment:
            CADSR_DS_HOST: $CADSR_DS_HOST
            CADSR_DS_PORT: $CADSR_DS_PORT
            CADSR_DS_PSWD: $CADSR_DS_PSWD
            TAG: cdebrowser-xlts-angularjs
        command: /tmp/build.sh
