version: '2'
services:
  server:
    container_name: cadsr-cde-browser11
    image: cadsr-cde-browser11
    build: ./
    ports:
     - "8084:8080"
    environment:
      CADSR_DS_HOST: $CADSR_DS_HOST
      CADSR_DS_PORT: $CADSR_DS_PORT
      CADSR_DS_USER: $CADSR_DS_USER
      CADSR_DS_PSWD: $CADSR_DS_PSWD
      CADSR_DS_TNS.ENTRY: $CADSR_DS_TNS_ENTRY
      tag: $tag
      tier: $tier
      JBOSS_MODULES_SYSTEM_PKGS: $JBOSS_MODULES_SYSTEM_PKGS
      JAVA_OPTS: $JAVA_OPTS
